title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
baseurl: /jekyll
website: https://tombaczynski.github.io
basewebsite: #/jekyll
